IMAGE_NAME := waja/testssl.sh

build:
	docker build --rm -t $(IMAGE_NAME) .
	
run:
	@echo docker run --rm -it $(IMAGE_NAME) 
	
shell:
	docker run --rm -it --entrypoint bash $(IMAGE_NAME) -l
